// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    private let lock = NSRecursiveLock()

    private var cached_userStorage: UserStorage?

    internal init() {
    }

    internal var userStorage: UserStorage {
        self.lock.lock()
        defer { self.lock.unlock() }
        if let cached = self.cached_userStorage { return cached }
        let userStorage = self.makeUserStorage()
        self.cached_userStorage = userStorage
        return userStorage
    }

    private func makeUserStorage() -> UserStorage {
        return UserStorage()
    }

}