// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    private let lock = NSRecursiveLock()

    private var cached_authorizer: Authorizer?

    private var cached_userStorage: UserStorage?

    internal init() {
    }

    internal var authorizer: Authorizer {
        self.lock.lock()
        defer { self.lock.unlock() }
        if let cached = self.cached_authorizer { return cached }
        let authorizer = self.makeAuthorizer()
        self.cached_authorizer = authorizer
        return authorizer
    }

    internal var userStorage: UserStorage {
        self.lock.lock()
        defer { self.lock.unlock() }
        if let cached = self.cached_userStorage { return cached }
        let userStorage = self.makeUserStorage()
        self.cached_userStorage = userStorage
        return userStorage
    }

    private func makeAuthorizer() -> Authorizer {
        return Authorizer(userStorage: self.userStorage)
    }

    private func makeUserStorage() -> UserStorage {
        return UserStorage()
    }

}