# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'SaberIOSGitHubRepoViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
end
