// Generated by Saber 0.1.3

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    private let lock = NSRecursiveLock()

    internal let appExternals: AppExternals

    private var cached_userManager: UserManager?

    internal init(appExternals: AppExternals) {
        self.appExternals = appExternals
    }

    internal var userManager: UserManager {
        self.lock.lock()
        defer { self.lock.unlock() }
        if let cached = self.cached_userManager { return cached }
        let userManager = self.makeUserManager()
        self.cached_userManager = userManager
        return userManager
    }

    internal var authorizerVC: AuthorizerVC {
        let authorizerVC = self.makeAuthorizerVC()
        return authorizerVC
    }

    private func makeUserManager() -> UserManager {
        return UserManager(appContainer: self, keychain: self.appExternals.keychain)
    }

    private func makeAuthorizerVC() -> AuthorizerVC {
        return AuthorizerVC(github: self.appExternals.github)
    }

    internal func injectTo(homeVC: HomeVC) {
        homeVC.makeAuthVC = { [unowned self] in return self.authorizerVC }
        homeVC.userManager = self.userManager
    }

}