# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'SaberIOSSessionExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaberIOSSessionExample
  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'SnapKit'
end
