// Generated by Saber 0.2.0

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    private var cached_consoleLogger: ConsoleLogger?

    internal init() {
    }

    internal var consoleLogger: ConsoleLogger {
        if let cached = self.cached_consoleLogger { return cached }
        let consoleLogger = self.makeConsoleLogger()
        self.cached_consoleLogger = consoleLogger
        return consoleLogger
    }

    internal var viewController: ViewController {
        let viewController = self.makeViewController()
        return viewController
    }

    private func makeConsoleLogger() -> ConsoleLogger {
        return ConsoleLogger()
    }

    private func makeViewController() -> ViewController {
        return ViewController(logger: self.consoleLogger)
    }

}