// Generated by Saber 0.2.0

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    private var cached_consoleLogger: ConsoleLogger?

    internal init() {
    }

    internal var consoleLogger: ConsoleLogger {
        if let cached = self.cached_consoleLogger { return cached }
        let consoleLogger = self.makeConsoleLogger()
        self.cached_consoleLogger = consoleLogger
        return consoleLogger
    }

    private func makeConsoleLogger() -> ConsoleLogger {
        return ConsoleLogger()
    }

    internal func injectTo(viewController: ViewController) {
        viewController.logger = self.consoleLogger
    }

}
